---
title: "Daten Visualisierung mit `ggplot2`"
---

## Schritt 1: Klone das Repository für Modul 2

1. Öffne github.com in deinem Browser.

2. Navigiere zur GitHub-Organisation für den Kurs: [github.com/rstatszh-k011](https://github.com/rstatszh-k011)

3. Finde das Repository [md-02-zusatzaufgaben-BENUTZERNAME]{.highlight-yellow}, das mit deinem GitHub-Benutzernamen endet, und öffne es in dem du darauf klickst.

4. Klicke auf die grüne Schaltfläche "Code".

5. Kopiere die HTTPS-URL in deine Zwischenablage.

6. Öffne den rstatszh-k011 Arbeitsbereich (Workspace) auf [posit.cloud](https://posit.cloud/spaces/598027/join?access_code=rYiY4Jmg-pU5XKJzRxZiCqeQjJqZ8YEfm7Vma8OV)

7. Klicke auf "New Project" > "New Project from Git Repository"

8. Füge die HTTPS-URL von GitHub in das Feld "URL of your Git Repository" ein. [**Beachte:**]{.highlight-yellow} Stelle sicher, dass die Box unter Packages ein Häkchen gesetzt hat.

9. Warte, bis das Projekt bereitgestellt wurde.

10. Öffne den Reiter "Files" im Fenster unten links und arbeite durch die Aufgaben in den folgenden zwei Dateien:

- `01-erstelle-diagramm.qmd`
- `02-daten-zusammenfassen.qmd`

11. Fahre mit dem nächsten Schritt 2 fort.

## Schritt 2: Übertrage deine Änderungen auf GitHub

1. Navigiere zum Git-Bereich im Fenster oben rechts.

2. Aktiviere die Kontrollkästchen neben allen Dateien, um sie für den Commit vorzubereiten.

3. Klicke auf die Schaltfläche "Commit".

4. Gib eine Commit-Nachricht in das Feld "Commit Message" ein (z.B. Zusatzaufgaben abgeschlossen).

5. Klicke auf die Schaltfläche "Commit". Das Fenster, welches sich daraufhin öffnet kann geschlossen werden.

::: callout-note
## Hinweis: Git configuration aus Zusatzaufgabe von Modul 1
Es ist möglich, dass Git dich erneut darauf hinweist, dass es nicht weiss, wer du bist. Diese Einstellung haben wir in Modul 1 zwar gemacht, jedoch habe ich in der Vergangenheit beobachtet, dass es bei einigen Teilnehmer:innen erneut zu dieser Meldung kommt. In diesem Fall musst du erneut folgenden Schritt ausführen, um deinen Namen und deine E-Mail-Adresse zu konfigurieren. 

```{r}
#| eval: false
library(usethis)
use_git_config(user.name = "Dein Name", user.email = "Deine Email")
```
:::

6. Klicke auf die Schaltfläche "Push".

7. Gib deinen GitHub-Benutzernamen im Feld Username an. 

8. Gib [deinen GitHub Personal Access Token (PAT)]{.highlight-yellow} im Feld ["Password"]{.highlight-yellow} ein.

9. Das Fenster kann geschlossen werden.

::: callout-important
## Verwende nicht dein GitHub-Passwort

Du musst GitHub Personal Access Token (PAT) eingeben, den du in der Vorbereitung auf den Kurs erstellt hast um deine Änderungen zurück an GitHub zu übertragen.
:::

## Schritt 3: Eröffne ein Issue auf GitHub

1. Öffne [github.com](https://github.com/) in deinem Browser.

2. Navigiere zur GitHub-Organisation für den Kurs: [github.com/rstatszh-k011](https://github.com/rstatszh-k011)

3. Finde das Repository [md-02-zusatzaufgaben-BENUTZERNAME]{.highlight-yellow}, das mit deinem GitHub-Benutzernamen endet.

4. Klicke auf die Schaltfläche "Issues".

5. Klicke auf die grüne Schaltfläche "New issue".

6. Schreibe in das Feld "Title": "Zusatzaufgaben abgeschlossen".

7. Markiere im Feld "Add a description" den Kursleiter mit @larnsce und hiterlasse eine Nachricht oder offene Frage.

