---
title: "Vorbereitung - rstatsZH Kurs 012"
editor: source
execute: 
  echo: false
  warning: false
editor_options: 
  chunk_output_type: console
---

Vielen Dank für dein Interesse an diesem Kurs. Dein Kursleiter [Lars Schöbitz](https://www.linkedin.com/in/larsschoebitz/) freut sich darauf, dich kennenzulernen. Falls du noch nicht für diesen Kurs angemeldet bist, dies aber gerne möchtest, dann nimm Kontakt über folgende Seite mit uns auf: <https://www.zh.ch/de/politik-staat/statistik-daten/datenkompetenz/datenkompetenz-verwaltung/rstatszh-data-science-mit-r-anmelden.html>.

Bist du zufällig auf diese Seite geraten? Mehr Informationen zum Konzept, Kursinhalten und Terminen gibt es hier: <https://rstats.zuerich/>

## {{< fa calendar >}} Wann findet dieser Kurs statt?

Wir treffen uns ab 21. Mai 2026 jeweils von 12:30 bis 15:00 Uhr auf MS Teams. Der Link wird über eine Kalendareinladung verschickt. 

Vor Tag 1 müsst ihr einige Aufgaben zur Vorbereitung auf den Kurs erledigen. Diese Vorarbeiten stellen sicher, dass wir unsere gemeinsame Zeit auf das Lernen konzentrieren können, anstatt die Infrastruktur einzurichten.

## {{< fa circle-question >}} Was muss ich vor Tag 1 vorbereiten?

Arbeite durch die folgenden Schritte: 

- [Schritt 1](vorbereitung/01-github.qmd): Erstelle ein Konto auf GitHub und richte ein GitHub Personal Access Token (PAT) ein.
- [Schritt 2](vorbereitung/02-posit-cloud.qmd): Melde dich bei Posit Cloud an und trete dem Arbeitsbereich für den Kurs bei.
- [Schritt 3](vorbereitung/03-r4ds-intro.qmd): Lies die Einführung des Kursbuches: R for Data Science.
- [Schritt 4](vorbereitung/04-umfrage.qmd): Fülle den Fragebogen bis Freitag, den 15. Mai 2026 aus.
