---
title: "Modul 9"
subtitle: "{{< var md-09.titel >}}"
editor: source
params:
    modul: 9
execute: 
  echo: false
  warning: false
bibliography: referenzen.bib
editor_options: 
  chunk_output_type: console
---

## Lernziele

```{r}
#| label: setup
#| include: false

library(epoxy)
library(dplyr)
library(here)

# Read variables from _variables.yml
vars <- yaml::read_yaml(here::here("_variables.yml"))

# Extract dates for this module
session_date <- vars$`md-09`$date |> as.Date()
homework_due_date <- vars$`md-09`$`homework-due` |> as.Date()

# Set locale for German date formatting
Sys.setlocale("LC_TIME", "de_DE.UTF-8")

# Format dates for display
session_date_formatted <- format(session_date, "%d. %B %Y")
homework_due_formatted <- format(homework_due_date, "%d. %B %Y")
```

```{r}
#| label: learning-objectives

lernziele <- readr::read_csv(here::here("data/tbl-01-rstatszh-lernziele.csv")) |>
  dplyr::filter(modul == params$modul) |>
  dplyr::pull(lernziele)

```

```{epoxy}
{1:length(lernziele)}. {lernziele[1:length(lernziele)]}
```

## {{< fa display >}} Folien

[Zeige Folien im Vollbildmodus an](../folien/md-09-quarto.html) | [Download slides as PDF]({{< var course.github-org >}}website/raw/main/folien/md-09-quarto.pdf)

```{=html}
<iframe class="slide-deck" src="../folien/md-09-quarto.html" height="420" width="747" style="border: 1px solid #123233;"></iframe>
```

## {{< fa book >}} Lesematerial

- Lies: [R for Data Science - Section 28 - Quarto](https://r4ds.hadley.nz/quarto)
- Lies: [R for Data Science - Section 29 - Quarto formats](https://r4ds.hadley.nz/quarto-formats)

## {{< fa code >}} Zusatzaufgabe

Bitte erledige die folgende Aufgabe bis **`r homework_due_formatted`**.

- [Zusatzaufgabe 1](../zusatzaufgaben/md-09/za-09-01-abschlussprojekt.qmd): Abschlussprojekt - Querverweise 